-- Add missing sports to the sport_type enum
ALTER TYPE sport_type ADD VALUE IF NOT EXISTS 'PICKLEBALL';
ALTER TYPE sport_type ADD VALUE IF NOT EXISTS 'RUNNING';
ALTER TYPE sport_type ADD VALUE IF NOT EXISTS 'CYCLING';
ALTER TYPE sport_type ADD VALUE IF NOT EXISTS 'BADMINTON';
ALTER TYPE sport_type ADD VALUE IF NOT EXISTS 'GOLF';